import { createClient } from '@supabase/supabase-js';
import nodemailer from 'nodemailer';
import crypto from 'crypto';

// 1. Initialize Supabase Service Role client (bypasses RLS for tracking/ingestion)
const supabaseUrl = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl) {
    console.error("Missing SUPABASE_URL environment variable.");
}
if (!supabaseServiceKey) {
    console.error("Missing SUPABASE_SERVICE_ROLE_KEY environment variable. Ingestion will fail RLS policies.");
}

const supabase = createClient(supabaseUrl || '', supabaseServiceKey || '', {
    auth: {
        persistSession: false,
        autoRefreshToken: false
    }
});

// 2. Initialize Nodemailer Transporter for Admin Alerts
// Falls back to mock logs if SMTP settings are missing
const smtpConfig = {
    host: process.env.SMTP_HOST || 'smtp.gmail.com',
    port: parseInt(process.env.SMTP_PORT || '587', 10),
    secure: (process.env.SMTP_PORT === '465'),
    auth: {
        user: process.env.SMTP_USER || '',
        pass: process.env.SMTP_PASS || ''
    }
};

const hasSmtpCredentials = process.env.SMTP_USER && process.env.SMTP_PASS;
const transporter = hasSmtpCredentials ? nodemailer.createTransport(smtpConfig) : null;
const notificationEmail = process.env.SMTP_FROM || 'impactvisuals2106@gmail.com';

/**
 * Sends SMTP Email notification to administrative address.
 */
async function sendAlertEmail(subject, text) {
    const mailOptions = {
        from: `"Growvex Analytics Alerts" <${notificationEmail}>`,
        to: 'impactvisuals2106@gmail.com',
        subject: `[Growvex Analytics] ${subject}`,
        text: text,
        html: `<div style="font-family: sans-serif; padding: 20px; background-color: #0d0e12; color: #e4e6eb; border-radius: 8px;">
            <h2 style="color: #6366f1; border-bottom: 1px solid #1f2937; padding-bottom: 10px;">Growvex Live Alert</h2>
            <p style="font-size: 16px; line-height: 1.5;">${text.replace(/\n/g, '<br>')}</p>
            <hr style="border: 0; border-top: 1px solid #1f2937; margin: 20px 0;">
            <p style="font-size: 12px; color: #9ca3af;">This is an automated alert generated by the Growvex Analytics system.</p>
        </div>`
    };

    if (transporter) {
        try {
            await transporter.sendMail(mailOptions);
            console.log(`[SMTP Alert Sent] ${subject}`);
            return true;
        } catch (error) {
            console.error('[SMTP Alert Failed]', error);
            return false;
        }
    } else {
        console.log(`[SMTP Alert Mocked (No SMTP Env)] ${subject}\nContent: ${text}`);
        return true;
    }
}

/**
 * Generates privacy-safe cryptographic hash of user IP.
 */
function hashIp(ip) {
    if (!ip) return 'unknown_ip';
    const salt = process.env.IP_HASH_SALT || 'growvex_default_ip_salt_12345';
    // Clean IP (e.g. ::ffff:127.0.0.1)
    const cleanIp = ip.replace(/^.*:/, '');
    return crypto.createHash('sha256').update(cleanIp + salt).digest('hex');
}

/**
 * Checks JWT Auth Token against Supabase Auth to confirm Admin status.
 */
async function verifyAdminAuth(req) {
    const authHeader = req.headers.authorization;
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
        return { authorized: false, error: 'Unauthorized: Missing token header.' };
    }

    const token = authHeader.split(' ')[1];
    try {
        // Build a temporary supabase client using the client authorization headers
        // This validates if the token is valid, matches a user, and returns their account metadata.
        const authClient = createClient(supabaseUrl || '', process.env.VITE_SUPABASE_ANON_KEY || '', {
            auth: {
                persistSession: false,
                autoRefreshToken: false
            }
        });

        const { data: { user }, error } = await authClient.auth.getUser(token);
        
        if (error || !user) {
            return { authorized: false, error: error ? error.message : 'Invalid Admin User session' };
        }

        // Grant access to specific admin emails
        const allowedAdmins = ['impactvisuals2106@gmail.com', 'veera@growvex.com', 'admin@growvex.app'];
        const isEmailAllowed = allowedAdmins.includes(user.email.toLowerCase()) || user.email.endsWith('@growvex.app');

        if (!isEmailAllowed) {
            return { authorized: false, error: 'Forbidden: Insufficient privileges.' };
        }

        return { authorized: true, user };
    } catch (err) {
        return { authorized: false, error: err.message };
    }
}

// 3. Basic in-memory rate limiting map (IP -> timestamp arrays)
const rateLimiterCache = new Map();
const LIMIT_WINDOW = 60 * 1000; // 1 minute
const MAX_REQUESTS = 60;        // Max 60 requests/min per clean IP

function checkRateLimit(ip) {
    if (!ip) return true;
    const now = Date.now();
    let requests = rateLimiterCache.get(ip) || [];
    
    // Clear out timestamps older than the window
    requests = requests.filter(time => now - time < LIMIT_WINDOW);
    
    if (requests.length >= MAX_REQUESTS) {
        return false;
    }
    
    requests.push(now);
    rateLimiterCache.set(ip, requests);
    return true;
}

// 4. Handle CORS headers
function setCorsHeaders(res) {
    res.setHeader('Access-Control-Allow-Credentials', true);
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
    res.setHeader(
        'Access-Control-Allow-Headers',
        'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version, Authorization'
    );
}

export {
    supabase,
    sendAlertEmail,
    hashIp,
    verifyAdminAuth,
    checkRateLimit,
    setCorsHeaders
};
